# fragment Types on ProjectTask {
#   ProjectTaskOpenType
#   ProjectTaskMultipleType
#   ProjectTaskYesOrNoType
# }

query allProjectTasks {
    allProjectTasks {
      ... on ProjectTaskProblemType {
        task {
          id
          order
          taskText
        }

      }	
      ... on ProjectTaskIdeaType{
        task {
          id
          order
          taskText
        }
      }
      ... on ProjectTaskActionType{
        task {
          id
          order
          taskText
        }
      }
      # project {
      #   projectName
      # }
      status
      submittedBy {
        username
      }
    }
  }