mutation updateProjectTaskProblem($taskId: ID!, $keywords: String) { 
    updateProjectTaskProblem(
      taskId: $taskId,
      keywords: $keywords
    ) {
      firstTouched
      lastTouched
      countTouched
      status
      task {
        id
        taskText
      }
      submittedBy {
        username
      }
    } 
  }

#   mutation {
#   updateUserAnswerMultiple(questionId: 72, answerChoiceKey: -1) {
#     firstTouched
#     lastTouched
#     countTouched
#     status
#     answerChoiceKey
#   }
# }
