mutation createUser($username: String!, $password: String!, $pollId: ID!) {
    createUser(
      username: $username,
      password: $password
      pollId : $pollId
    ) {
      user {
        username
        currentPoll {
          pollName
        }
      }
    }
  }
